### ISSUE TITLE
Different redirect URI/authorization callback?

### ISSUE THREAD

**Issue by frafra** [apache/incubator-answer-plugins#1]
I enabled `/answer/api/v1/connector/login/basic` as callback, as suggested in `README.md`, but the OAuth shows that the request is using `/answer/api/v1/connector/redirect/basic`.

https://github.com/answerdev/plugins/blob/b35f4c06e51527f68d62dded9966490847344197/connector/basic/README.md?plain=1#L30

**Comment by cdhunt** [comment]
Is it `{SiteURL}/answer/api/v1/connector/redirect/basic` or `{SiteUrl}/api/v1/connector/redirect/basic`?
