### ISSUE TITLE
Add LaTex math equation support

### ISSUE THREAD

**Issue by hhhguany** [apache/incubator-answer-plugins#121]
## Is your feature request related to a problem? Please describe

As of the current version of Answer, it is impossible to insert Latex equations, which significantly limits the notation experience for users working with mathematical and scientific data. The lack of this feature represents a considerable challenge when attempting to represent complex mathematical models in the project.

## Describe the solution you'd like

Adding support for Mathjax can solve this issue.

**Comment by hhhguany** [comment]
In the questioning part, the rendering is correct, but the answering part is wrong.

<img width="764" alt="image" src="https://github.com/apache/incubator-answer/assets/12447542/948c6e78-797d-43e7-bdb9-a51c70da5715">

<img width="320" alt="image" src="https://github.com/apache/incubator-answer/assets/12447542/ab708aeb-3ed5-4e05-bf66-cd673d77f1d0">

**Comment by robinv8** [comment]
Thank you for your feedback. The bug has been reproduced and will be fixed in the next version.

**Comment by hhhguany** [comment]
Thank you for your work.
