### ISSUE TITLE
Need code line high-light

### ISSUE THREAD

**Issue by coanor** [apache/incubator-answer-plugins#16]
**Is your feature request related to a problem? Please describe.**
For large code blocks, we need high-light effect on specific lines, these high light lines are better to explain and anwser the question.

**Describe the solution you'd like**
Like code line high-light in [mkdocs material](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines), the high-light syntax looks like this:

    ``` py hl_lines="2 3"
    def bubble_sort(items):
        for i in range(len(items)):
            for j in range(len(items) - 1 - i):
                if items[j] > items[j + 1]:
                    items[j], items[j + 1] = items[j + 1], items[j]
    ```
and we get the effect:

![image](https://user-images.githubusercontent.com/841781/223306343-4f991432-30b4-4278-a45f-ddd8ea5576b3.png)

**Comment by Kota-Karthik** [comment]
@coanor I am interested in doing this issue 
so kindly assign me this

**Comment by fenbox** [comment]
@Kota-Karthik Thank you. Looking forward to it.
