### ISSUE TITLE
How does the embed plugin work? There is no render github link

### ISSUE THREAD

**Issue by woodchen-ink** [apache/incubator-answer-plugins#189]
![image](https://github.com/user-attachments/assets/82e4aa2d-0d36-4854-b06f-0a08a45db5ac)
So far it looks like this, I thought it was going to be the same as discourse
![image](https://github.com/user-attachments/assets/5a44d3f5-69e1-41fe-9d77-d8ab8778d483)

**Comment by woodchen-ink** [comment]
Even the youtube link cannot be parsed correctly, for example: https://www.youtube.com/watch?v=VINZeWNhgIU. I don’t understand how to call this plug-in. The background options are already turned on.

![image](https://github.com/user-attachments/assets/789e0745-9d3b-405a-b199-3898b685a5ce)

**Comment by robinv8** [comment]
What is the version of Answer?

**Comment by woodchen-ink** [comment]
> What is the version of Answer?
> 
> Regarding GitHub, currently, only GitHub gist is supported.
> 
> ![image](https://private-user-images.githubusercontent.com/12277531/353410560-58d904de-cd5c-419e-8256-b0585918f252.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDEwNjQsIm5iZiI6MTcyMjM0MDc2NCwicGF0aCI6Ii8xMjI3NzUzMS8zNTM0MTA1NjAtNThkOTA0ZGUtY2Q1Yy00MTllLTgyNTYtYjA1ODU5MThmMjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDExNTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OWE3Yjc4YzVjOWNhZDNiODc0ZDQ2ODU5ZjJkZTk0ODU2ODM2YmQ5MmJlZGMwMDU5NGRjYThhMGJhZDBhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MU1dP5SrWQPXdW4VO6NNj7CxJvZgRZBCROw_nWbGH-c)
> 
> ![image](https://private-user-images.githubusercontent.com/12277531/353412022-02237e41-a1eb-4128-98b5-605a83e8476e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDEwNjQsIm5iZiI6MTcyMjM0MDc2NCwicGF0aCI6Ii8xMjI3NzUzMS8zNTM0MTIwMjItMDIyMzdlNDEtYTFlYi00MTI4LTk4YjUtNjA1YTgzZTg0NzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDExNTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NDQxMzA2M2NiOGUzNTlmNDcwZjQxNTUwOGNmNzEyMzM4NDFjODhjNTVkYjllOTAwZTExZjY1ZGYxMDMyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RZwG0Sk8Xhzv97yRovLbdWDBLbySC-MU11NJtx7PlkI)

1.3.6 ， i will try again later

**Comment by robinv8** [comment]
My Answer version is also 1.3.6, so can you check what the Embed plugin version is?

**Comment by woodchen-ink** [comment]
> My Answer version is also 1.3.6, so can you check what the Embed plugin version is?

My plugin is up to date, and I found that I modified the code of `embed_controller.go`, because the site was migrated once, and the error: `[interface {} is string, not bool]`, caused the page to not load properly. Then I fixed the error with the help of claude 3.5, but I didn't test if the embedding worked, I will restore the code and test again. I suspect it's because my MySQL version was originally 5.7 and the new server is MySQL 8.0, which caused this error

**Comment by woodchen-ink** [comment]
![image](https://github.com/user-attachments/assets/49940d01-e1b7-4eea-9a71-bf96f35e9a28)

## Error log
```
2024-07-31 12:58:56.528	ERROR	runtime/panic.go:890	http: panic serving 172.18.0.1:47068: interface conversion: interface {} is string, not bool
goroutine 504 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xb8
panic({0x1168c60, 0x4002b98e40})
	/usr/local/go/src/runtime/panic.go:890 +0x260
github.com/apache/incubator-answer/internal/controller.(*EmbedController).GetEmbedConfig.func2({0xe2dc790a2968, 0x400054ee98})
	/go/src/github.com/apache/incubator-answer/answer_build3308615552/vendor/github.com/apache/incubator-answer/internal/controller/embed_controller.go:58 +0x24c
github.com/apache/incubator-answer/plugin.MakePlugin[...].func1()
	/go/src/github.com/apache/incubator-answer/answer_build3308615552/vendor/github.com/apache/incubator-answer/plugin/plugin.go:134 +0x150
github.com/apache/incubator-answer/internal/controller.(*EmbedController).GetEmbedConfig(0x4003121050?, 0x4002c86200?)
	/go/src/github.com/apache/incubator-answer/answer_build3308615552/vendor/github.com/apache/incubator-answer/internal/controller/embed_controller.go:53 +0x138
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/src/github.com/apache/incubator-answer/answer_build3308615552/vendor/github.com/gin-gonic/gin/context.go:174
github.com/anargu/gin-brotli.Brotli.func1(0x4002c86200)
	/go/src/github.com/apache/incubator-answer/answer_build3308615552/vendor/github.com/anargu/gin-brotli/gin_brotli.go:71 +0x1d8
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/src/github.com/apache/incubator-answer/answer_build3308615552/vendor/github.com/gin-gonic/gin/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0x400010ed00, 0x4002c86200)
	/go/src/github.com/apache/incubator-answer/answer_build3308615552/vendor/github.com/gin-gonic/gin/gin.go:620 +0x560
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0x400010ed00, {0x3bf9d88?, 0x4003674460}, 0x4001c70100)
	/go/src/github.com/apache/incubator-answer/answer_build3308615552/vendor/github.com/gin-gonic/gin/gin.go:576 +0x1fc
net/http.serverHandler.ServeHTTP({0x4002dfe540?}, {0x3bf9d88, 0x4003674460}, 0x4001c70100)
	/usr/local/go/src/net/http/server.go:2947 +0x2cc
net/http.(*conn).serve(0x400040ff40, {0x3bfaa98, 0x4001bcf710})
	/usr/local/go/src/net/http/server.go:1991 +0x544
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x43c
```
## In the database, it's like this
![image](https://github.com/user-attachments/assets/5ed77e86-9a45-4139-a3d0-78f48f062ca9)

---  

I don't understand why this plugin isn't working

**Comment by woodchen-ink** [comment]
mysql 8.2.0

**Comment by robinv8** [comment]
Check whether the plugin field `enabled` returned by the `/answer/api/v1/plugin/status` interface is `true`, and then observe whether the Chrome console reports an error.

**Comment by woodchen-ink** [comment]
```
{"code":200,"reason":"base.success","msg":"Success.","data":[{"slug_name":"basic_reviewer","enabled":true},
{"slug_name":"akismet_reviewer","enabled":true},{"slug_name":"basic_captcha","enabled":true},
{"slug_name":"s3_storage","enabled":true},{"slug_name":"algolia-search","enabled":true},
{"slug_name":"redis_cache","enabled":true},{"slug_name":"basic_embed","enabled":true},
{"slug_name":"chart_editor","enabled":true},{"slug_name":"formula_editor","enabled":true},
{"slug_name":"github_connector","enabled":true},{"slug_name":"google_connector","enabled":true}]}

```
![image](https://github.com/user-attachments/assets/f154a875-7226-4cca-9c30-bc9d4136c992)
![image](https://github.com/user-attachments/assets/1d156fe2-0ef1-44cd-a1be-231a768037d6)
![image](https://github.com/user-attachments/assets/9e6970f5-ac90-4b68-b886-9ea2a609d442)
![image](https://github.com/user-attachments/assets/7c8cfee0-7311-4b9f-896d-f0be7df88d06)

**Comment by woodchen-ink** [comment]
Once this plugin is enabled, all question pages cannot be displayed properly

**Comment by robinv8** [comment]
After closing the plugin, other interfaces are normal?

**Comment by woodchen-ink** [comment]
> After closing the plugin, other interfaces are normal? Please open the plugin and visit q58.org to try it.

After closing this plugin, all functions are normal. Do you need me to open it now for you to check?

**Comment by robinv8** [comment]
> > After closing the plugin, other interfaces are normal? Please open the plugin and visit q58.org to try it.
> 
> After closing this plugin, all functions are normal. Do you need me to open it now for you to check?

Yes.

**Comment by woodchen-ink** [comment]
> > > After closing the plugin, other interfaces are normal? Please open the plugin and visit q58.org to try it.
> > 
> > 
> > After closing this plugin, all functions are normal. Do you need me to open it now for you to check?
> 
> Yes.

OK, I open it already

**Comment by woodchen-ink** [comment]
If you have checked it, please leave a message, thank you. Otherwise, the content of the article cannot be accessed normally.

**Comment by robinv8** [comment]
Related to the `/answer/api/v1/embed/config` interface, which returns the enabled embed type, for example:
```
{
    "code": 200,
    "reason": "base.success",
    "msg": "Success.",
    "data": [
        {
            "platform": "CodePen",
            "enable": true
        },
        {
            "platform": "Dropbox",
            "enable": true
        },
        {
            "platform": "Excalidraw",
            "enable": true
        },
        {
            "platform": "Figma",
            "enable": true
        },
        {
            "platform": "GithubGist",
            "enable": true
        },
        {
            "platform": "JSFiddle",
            "enable": true
        },
        {
            "platform": "Loom",
            "enable": true
        },
        {
            "platform": "Twitter",
            "enable": true
        },
        {
            "platform": "YouTube",
            "enable": true
        }
    ]
}
```
I asked the plugin developer to check this issue.

**Comment by woodchen-ink** [comment]
Thank you very much

**Comment by woodchen-ink** [comment]
I would like to add some information: I am running on an ARM machine, which may be related to the platform
![image](https://github.com/user-attachments/assets/f211733c-3c75-4195-86b9-2ee2de1f19b4)

**Comment by kumfo** [comment]
Sorry, this is a bug.
 
When defining the Embed plugin, the data structure is consistent with the Basic plugin, resulting in other installed plugins being recognized as the Embed plugin.
 
I will make corrections in the next version.
 
If you need to use it urgently and install it from source code, you can temporarily manually make changes to the source code before compiling and installing it.
 
Change the code location:

[Code Line](https://github.com/apache/incubator-answer/blob/4692420e5ff366f7d7e0d5d14a2afab1527cbd0b/internal/controller/embed_controller.go#L44)

The code changed:
```go
func (c *EmbedController) GetEmbedConfig(ctx *gin.Context) {
	resp := make([]*schema.GetEmbedOptionResp, 0)

	_ = plugin.CallConfig(func(fn plugin.Config) error {
		if fn.Info().SlugName == "basic_embed" {
			for _, field := range fn.ConfigFields() {
				resp = append(resp, &schema.GetEmbedOptionResp{
					Platform: field.Name,
					Enable:   field.Value.(bool),
				})
			}
			return nil
		}
		return nil
	})
	handler.HandleResponse(ctx, nil, resp)
}
```

**Comment by woodchen-ink** [comment]
Thank you very much, I will modify the source code, compile and install it, and I will test it again. It may take 2 hours.

I will leave a message again after testing.

**Comment by woodchen-ink** [comment]
![image](https://github.com/user-attachments/assets/bcfe42d2-faed-4de3-8b37-24863d705b24)
![image](https://github.com/user-attachments/assets/3dee9f58-c7d9-4d45-bdf0-436cc3a514a2)
This plugin works, thank you for your support
