### ISSUE TITLE
Algolia Search - Virtual replicas are not enabled on this plan

### ISSUE THREAD

**Issue by gareth-johnstone** [apache/incubator-answer-plugins#205]
We installed the Algolia search plugin on our instance of Apache Answers - we immediately started getting API errors because the contents was larger than 10kb (we have some very in depth Q&A)

We then decided to upgrade to the "Grow" plan that Algolia offer but as soon as we hit the save button in the admin area we are presented with an error 50x and if we take a closer look at the API log we see the following:

`Virtual replicas are not enabled on this plan`

So we have no way of using this.

**Comment by robinv8** [comment]
Thanks for your feedback, I will follow up on this issue.

**Comment by kumfo** [comment]
Due to performance and query reasons, using Algolia search requires reliance on virtual replicas. You can check which plan of Algolia supports virtual replicas, and it is best to upgrade to a plan that supports them.

I test algolia search with free plan only, if Algolia has limitations, see if you can build an ElasticSearch service yourself. We also provide plugins for ElasticSearch.

**Comment by gareth-johnstone** [comment]
> Due to performance and query reasons, using Algolia search requires reliance on virtual replicas. You can check which plan of Algolia supports virtual replicas, and it is best to upgrade to a plan that supports them.
> 
> I test algolia search with free plan only, if Algolia has limitations, see if you can build an ElasticSearch service yourself. We also provide plugins for ElasticSearch.

The problem with Elastic Search is that there is no 1st time sync (we imported a load of data)
(we also have a further issue where none of these offer search on comments)

**Comment by gareth-johnstone** [comment]
> Due to performance and query reasons, using Algolia search requires reliance on virtual replicas. You can check which plan of Algolia supports virtual replicas, and it is best to upgrade to a plan that supports them.
> 
> I test algolia search with free plan only, if Algolia has limitations, see if you can build an ElasticSearch service yourself. We also provide plugins for ElasticSearch.

The problem with Aloglia search, once you go past the Pay as you go plan, it gets VERY expensive very fast, so I don't think its a viable option.

Thanks for looking into it though.
