### ISSUE TITLE
How do I support formulas in the body?

### ISSUE THREAD

**Issue by obiscr** [apache/incubator-answer-plugins#243]
I've added the `editor-formula` with this command

```
./answer build --with github.com/apache/incubator-answer-plugins/editor-formula
```

It works well

![](https://meta.answer.dev/uploads/post/5iH8Rn1MsWU.png)

But in the question content, it's still shown as plain text, not formula.

![](https://meta.answer.dev/uploads/post/5iH927YVMUu.png)

How to fix this?

Versions:
editor-formula: 1.2.11
answer: 1.4.0

**Comment by obiscr** [comment]
Wow, thanks for fixing it so quickly!

**Comment by obiscr** [comment]
@robinv8 I'm try to rebuile the plugin, but I got this.
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/d653a604-801e-45ad-8654-0b2cfe6d08dc">

**Comment by robinv8** [comment]
@obiscr To specify the version, use: editor-formula@v1.2.12
