### ISSUE TITLE
connector-dingtalk error 500

### ISSUE THREAD

**Issue by Xiaohantx** [apache/incubator-answer-plugins#261]
![微信截图_20241205161005](https://github.com/user-attachments/assets/6f856f7e-51bc-440f-83fe-9a906f4819dd)
![微信截图_20241205161057](https://github.com/user-attachments/assets/7bf8c31a-c66c-4982-80be-a0584b44675d)
![微信截图_20241205161106](https://github.com/user-attachments/assets/e447e409-b2c6-496d-ab0c-fcf9a28d1b10)

It can normally click the login button and redirect to the login center, but after confirming, it returns to the page with a 500 error. I have configured all the related content.

**Comment by sy-records** [comment]
It was fine when I tested it, you need to check the error messages in the logs.

You might have forgotten to apply the dingtalk permissions.

**Comment by Xiaohantx** [comment]
@LinkinStars @sy-records 
Indeed, thank you. The permission needs to be enabled, and it works after I manually enabled it.
