### ISSUE TITLE
`answer build` with meilisearch plugin failing.

### ISSUE THREAD

**Issue by heubeck** [apache/incubator-answer-plugins#53]
When running 

```
answer build --with github.com/apache/incubator-answer-plugins/search-meilisearch
```

If fails with 

```
[go build -ldflags -X github.com/apache/incubator-answer/cmd.Version=1.2.1 -X github.com/apache/incubator-answer/cmd.Revision=3f696b6 -X github.com/apache/incubator-answer/cmd.Time=1702543995 -o /new_answer .]
# github.com/apache/incubator-answer-plugins/search-meilisearch
vendor/github.com/apache/incubator-answer-plugins/search-meilisearch/meilisearch.go:327:70: cannot use tagGroup (variable of type string) as []string value in argument to strings.Join
build failed exit status 1
```

Tried also different refs like  `github.com/apache/incubator-answer-plugins/search-meilisearch@main`, did not manage to get around the error.

`answer -v`: 

```
answer version 1.2.1
revision: 3f696b6
build time: 1702543995
```

build environment based on the official answer docker image: 

```
FROM apache/answer:1.2.1 as builder

RUN apk --no-cache add \
    build-base git bash nodejs npm go && \
    npm install -g pnpm

RUN answer build \
    --with github.com/apache/incubator-answer-plugins/connector-basic \
    --with github.com/apache/incubator-answer-plugins/search-meilisearch \
    --output /usr/local/bin/answer_with_plugins
```

**Comment by hbsciw** [comment]
@LinkinStars Can you suggest Any workaround to build with meilisearch?

**Comment by heubeck** [comment]
yes, the references are the same:

![image](https://github.com/apache/incubator-answer-plugins/assets/40993644/b8476a06-c16d-4ce5-b5e9-011e082c5bde)

I'm testing within a docker build, so no caches at all.

thx for caring :heart_decoration:

**Comment by heubeck** [comment]
> Sounds good. We can fix what you said with the `search-meilisearch/v1.2.1` tag. For example, for now you can do it via `./answer build --with github.com/apache/incubator-answer-plugins/search-meilisearch@v1.2.1` command to pull this version of the plugin.

awesome, thx, @LinkinStars.
Can you create similar tags for the other plugins as well?

**Comment by heubeck** [comment]
Thx so much!
