### ISSUE TITLE
user-center-wecom can't login normal

### ISSUE THREAD

**Issue by zeallean** [apache/incubator-answer-plugins#88]
As the title desc. When I install the plugin and add the setting normally. But the login is error when i scan the qcode.
It is the error msg in the docker container log.
![image](https://github.com/apache/incubator-answer-plugins/assets/1608741/ee89f396-1e47-4794-8ac0-04d037e54c1e)

**Comment by lucifer-Technoking** [comment]
and I can not sign up by using email address after wecom plugin is enabled

**Comment by lucifer-Technoking** [comment]
got it, two different categories
